#############################################################################
# Makefile for building: main
# Generated by qmake (3.0) (Qt 5.6.3)
# Project:  913.pro
# Template: app
# Command: /home/kienlm/workspace/Qt5.6.3/5.6.3/gcc_64/bin/qmake -o Makefile 913.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../workspace/Qt5.6.3/5.6.3/gcc_64/include -I../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtMultimedia -I../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtNetwork -I../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtGui -I../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore -I. -I../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/linux-g++
QMAKE         = /home/kienlm/workspace/Qt5.6.3/5.6.3/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = main1.0.0
DISTDIR = /home/kienlm/rtp_913/.tmp/main1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/kienlm/workspace/Qt5.6.3/5.6.3/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/kienlm/workspace/Qt5.6.3/5.6.3/gcc_64/lib -lQt5Multimedia -L/usr/lib64 -L/home/dicom/workspace/Qt5.6.3/5.6.3/gcc_64/lib -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = ../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/spec_pre.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/unix.conf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/linux.conf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/sanitize.conf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/gcc-base.conf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/g++-base.conf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/g++-unix.conf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/qconfig.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/qt_functions.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/qt_config.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/spec_post.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/default_pre.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/resolve_config.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/default_post.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/warn_on.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/qt.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/resources.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/moc.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/unix/thread.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/file_copies.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/exceptions.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/yacc.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/lex.prf \
		913.pro  main.cpp
QMAKE_TARGET  = main
DESTDIR       = 
TARGET        = main


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 913.pro ../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/linux-g++/qmake.conf ../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/spec_pre.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/unix.conf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/linux.conf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/sanitize.conf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/gcc-base.conf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/g++-base.conf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/g++-unix.conf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/qconfig.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/qt_functions.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/qt_config.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/spec_post.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/default_pre.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/resolve_config.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/default_post.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/warn_on.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/qt.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/resources.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/moc.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/unix/thread.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/file_copies.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/exceptions.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/yacc.prf \
		../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/lex.prf \
		913.pro \
		../workspace/Qt5.6.3/5.6.3/gcc_64/lib/libQt5Multimedia.prl \
		../workspace/Qt5.6.3/5.6.3/gcc_64/lib/libQt5Network.prl \
		../workspace/Qt5.6.3/5.6.3/gcc_64/lib/libQt5Gui.prl \
		../workspace/Qt5.6.3/5.6.3/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile 913.pro
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/spec_pre.prf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/unix.conf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/linux.conf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/sanitize.conf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/gcc-base.conf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/g++-base.conf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/g++-unix.conf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/qconfig.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_location.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/qt_functions.prf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/qt_config.prf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/linux-g++/qmake.conf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/spec_post.prf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/exclusive_builds.prf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/default_pre.prf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/resolve_config.prf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/default_post.prf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/warn_on.prf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/qt.prf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/resources.prf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/moc.prf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/unix/opengl.prf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/unix/thread.prf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/file_copies.prf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/testcase_targets.prf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/exceptions.prf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/yacc.prf:
../workspace/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/lex.prf:
913.pro:
../workspace/Qt5.6.3/5.6.3/gcc_64/lib/libQt5Multimedia.prl:
../workspace/Qt5.6.3/5.6.3/gcc_64/lib/libQt5Network.prl:
../workspace/Qt5.6.3/5.6.3/gcc_64/lib/libQt5Gui.prl:
../workspace/Qt5.6.3/5.6.3/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile 913.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp ../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/QByteArray \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qbytearray.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qrefcount.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qglobal.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qconfig.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qfeatures.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qsystemdetection.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qprocessordetection.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qtypeinfo.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qtypetraits.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qisenum.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qsysinfo.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qlogging.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qflags.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qglobalstatic.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qmutex.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qnumeric.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qversiontagging.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qbasicatomic.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qgenericatomic.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_x86.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_unix.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qnamespace.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qarraydata.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qstring.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qchar.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qstringbuilder.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtNetwork/QHostAddress \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtNetwork/qhostaddress.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qpair.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qscopedpointer.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtNetwork/qabstractsocket.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qiodevice.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qobject.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qobjectdefs.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qlist.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qalgorithms.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qiterator.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qhashfunctions.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qbytearraylist.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qstringlist.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qregexp.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qstringmatcher.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qcoreevent.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qmetatype.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qobject_impl.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qdebug.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qhash.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qmap.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qtextstream.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qlocale.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qvariant.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qshareddata.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qvector.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qpoint.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qset.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtNetwork/QUdpSocket \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtNetwork/qudpsocket.h \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/QThread \
		../workspace/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

